---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-apt
    - curl
    - jq
    - docker.io
    - unzip
    - netfilter-persistent
    - iptables-persistent
    - socat
